// <auto-generated />
using DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20231011132921_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BusinessLogic.Entities.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Name = "Silver"
                        },
                        new
                        {
                            Id = 1,
                            Name = "Black"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Space Black"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Space Grey"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Deep Purple"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Starlight"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Green"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Gold"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Sierra Blue"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Midnight"
                        });
                });

            modelBuilder.Entity("BusinessLogic.Entities.Phone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<int>("Memory")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.ToTable("Phones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorId = 10,
                            Description = "A total powerhouse.",
                            ImageUrl = "https://estore.ua/ua/media/catalog/product/cache/9/image/600x600/9df78eab33525d08d6e5fb8d27136e95/i/p/iphone-14-finish-select-202209-6-1inch-midnight_1.png",
                            Memory = 128,
                            Model = "iPhone 14",
                            Price = 799m
                        },
                        new
                        {
                            Id = 2,
                            ColorId = 6,
                            Description = "Big and bigger.",
                            ImageUrl = "https://estore.ua/ua/media/catalog/product/cache/9/image/600x600/9df78eab33525d08d6e5fb8d27136e95/i/p/iphone-14-plus_2__3.jpeg",
                            Memory = 128,
                            Model = "iPhone 14 Plus",
                            Price = 899m
                        },
                        new
                        {
                            Id = 3,
                            ColorId = 3,
                            Description = "The ultimate iPhone.",
                            ImageUrl = "https://estore.ua/ua/media/catalog/product/cache/9/image/600x600/9df78eab33525d08d6e5fb8d27136e95/1/4/14pro-promax-black-1_4_2.jpeg",
                            Memory = 256,
                            Model = "iPhone 14 Pro",
                            Price = 1099m
                        },
                        new
                        {
                            Id = 4,
                            ColorId = 5,
                            Description = "Pro. Beyond.",
                            ImageUrl = "https://estore.ua/ua/media/catalog/product/cache/9/image/600x600/9df78eab33525d08d6e5fb8d27136e95/1/4/14pro-promax-purple-1_9.jpeg",
                            Memory = 512,
                            Model = "iPhone 14 Pro Max",
                            Price = 1399m
                        });
                });

            modelBuilder.Entity("BusinessLogic.Entities.Phone", b =>
                {
                    b.HasOne("BusinessLogic.Entities.Color", "Color")
                        .WithMany("Phones")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Color");
                });

            modelBuilder.Entity("BusinessLogic.Entities.Color", b =>
                {
                    b.Navigation("Phones");
                });
#pragma warning restore 612, 618
        }
    }
}
